apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  description: CI/CD pipeline: cleanup -> clone -> (lint & tests) -> build -> deploy
  params:
    - name: repo-url
      type: string
      description: Git repository URL
    - name: branch
      type: string
      default: main
    - name: build-image
      type: string
      description: Fully-qualified image (registry/namespace/name:tag)
  workspaces:
    - name: pipeline-workspace

  tasks:
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
        - name: depth
          value: "1"
        - name: submodules
          value: "true"
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: lint
      runAfter: [clone]
      taskRef:
        name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: args
          value: "."

    - name: tests
      runAfter: [clone]
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value: "-v --with-spec --spec-color"

    - name: build
      runAfter: [lint, tests]
      taskRef:
        name: build-and-push
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: $(params.build-image)

    - name: deploy
      runAfter: [build]
      taskRef:
        name: oc
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: $(params.build-image)
