apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: IMAGE_NAME_HERE
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-uri
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  selector:
    app: accounts
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
