apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          # The pipeline's deploy task will set/replace this image
          image: IMAGE_NAME_HERE
          ports:
            - containerPort: 8080
          env:
            # Use a single connection string from the 'postgresql' Secret
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-uri
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  selector:
    app: accounts
  ports:
    - name: http
      port: 8080
      targetPort: 8080
