apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - image: IMAGE_NAME_HERE
        name: accounts
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URI
          value: postgresql://postgres:postgres@postgresql:5432/accounts
      restartPolicy: Always
